### ISSUE TITLE
Api project?

### ISSUE THREAD

**Issue by creio** [Swetrix/selfhosting#7]
Hello, why doesn't the projects API work?

`curl -i -X POST https://api.example.com/v1/project -H "X-Api-Key: ${SWETRIX_API_KEY}" -H "Content-Type: application/json" -d '{"name": "test pub","public": true}'`

`{"message":"Cannot POST /v1/project","error":"Not Found","statusCode":404}`

and another thing is that the wrong URL is being substituted in the settings.

![изображение](https://github.com/user-attachments/assets/4b82e2a7-18c4-4c7d-b7ac-69279ee71663)

**Comment by Blaumaus** [comment]
Hi! I just realised I forgot to add `v1` prefix for project-related endpoints on self-hosted version.

Can you try to use
`curl -i -X POST https://api.example.com/v1/project -H "X-Api-Key: ${SWETRIX_API_KEY}" -H "Content-Type: application/json" -d '{"name": "test pub","public": true}'` instead?

This issue will be fixed in the next selfhosted release.

**Comment by creio** [comment]
![изображение](https://github.com/user-attachments/assets/98d2f5ac-2c28-46a7-8e27-313840170ae6)

**Comment by Blaumaus** [comment]
I found the issue, the API keys will not work on `project` related endpoints, it was an oversight on our side.
I'll fix this and try to release a new version this / next week. Sorry for that

**Comment by Blaumaus** [comment]
This issue should be fixed in [v3.2.0](https://github.com/Swetrix/swetrix-api/releases/tag/v3.2.0)
